### ISSUE TITLE
Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by Ugarz** [webmakersteve/battle-net.js#6]
Hello,
I've started to use you library. While i was using it, I went throught this :
```
/Users/ugoa/dev/perso/HarryBotteur/node_modules/battlenet.js/lib/api-client.js:80
    if (contentType.indexOf(';')) {
                   ^

TypeError: Cannot read property 'indexOf' of undefined
    at Request._callback (/Users/ugoa/dev/perso/HarryBotteur/node_modules/battlenet.js/lib/api-client.js:80:20)
    at Request.self.callback (/Users/ugoa/dev/perso/HarryBotteur/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at Request.<anonymous> (/Users/ugoa/dev/perso/HarryBotteur/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at IncomingMessage.<anonymous> (/Users/ugoa/dev/perso/HarryBotteur/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:91:20)
[nodemon] app crashed - waiting for file changes before starting...
```

I think that in your `api-client.js:80`, you can't get the `contentType` var, that's why it's breaking up. I think the battlenet api may not find any information on my character but if there is no response, you can't get headers.

**Comment by Ugarz** [comment]
In fact, logging `api-client:80` say that you check for a `'content-type'` who does not exists in response :
```
response.headers { 'content-length': '0', connection: 'Close' }
/Users/ugoa/dev/perso/HarryBotteur/node_modules/battlenet.js/lib/api-client.js:82
    if (contentType.indexOf(';')) {
```
You should probably check for a key in this object `{ 'content-length': '0', connection: 'Close' }` and if it's here it says that no content been found (and that is why you `response.body` is empty).

**Comment by maxtruxa** [comment]
@Ugarz This issue is fixed since [this commit](https://github.com/webmakersteve/battle-net.js/commit/c4c8a228d27b0c7d290e35b4985a99d3fc3a202c). It just hasn't been published yet.

@webmakersteve Could you publish the current master to npm?

**Comment by webmakersteve** [comment]
Published. Sorry for the delay.
